=== root-project/root/roofit/etc/HistFactorySchema.dtd
<!-- The top level combination spec -->
<!-- OutputFilePrefix: Prefix to the output root file to be created (inspection histograms) -->
<!-- Mode: Type of the analysis -->
<!ELEMENT Combination (Function*,Input+,Measurement*)>
<!ATTLIST Combination
        OutputFilePrefix         CDATA            #REQUIRED
        Mode                     CDATA            #IMPLIED
>

<!-- Input files detailing the channels. One channel per file -->
<!ELEMENT Function  EMPTY>
<!ATTLIST Function
     Name                 CDATA         #REQUIRED
     Expression           CDATA         #REQUIRED
     Dependents           CDATA         #REQUIRED
>

<!-- Input files detailing the channels. One channel per file -->
<!ELEMENT Input (#PCDATA) >

<!-- Configuration for each measurement -->
<!-- Name: to be used as the heading in the table -->
<!-- Lumi: the luminosity of the measurement -->
<!-- LumiRelErr: the relative error known for the lumi -->
<!-- BinLow: the lowest bin number used for the measurement (inclusive) -->
<!-- BinHigh: the highest bin number used for the measurement (exclusive) -->
<!-- Mode: type of the measurement (a closed list of ...) -->
<!-- ExportOnly: if "True" skip fit, only export model -->
<!ELEMENT Measurement (POI,ParamSetting*,ConstraintTerm*) >
<!ATTLIST Measurement
        Name              CDATA            #REQUIRED
        Lumi              CDATA            #REQUIRED
        LumiRelErr        CDATA            #REQUIRED
        BinLow            CDATA            #IMPLIED
        BinHigh           CDATA            #IMPLIED
        Mode              CDATA            #IMPLIED
        ExportOnly        CDATA            #IMPLIED
>

<!-- Specify what you are measuring. Corresponds to the name specified in the construction
of the model in the channel setup. Typically the NormFactor for xsec measurements -->
<!ELEMENT POI (#PCDATA) >

<!-- Specify what parameters are fixed, or have particular value -->
<!-- Val: set the value of the parameter -->
<!-- Const: set this parameter constant -->
<!ELEMENT ParamSetting (#PCDATA)>
<!ATTLIST ParamSetting
        Val               CDATA           #IMPLIED
        Const             CDATA           #IMPLIED
>

<!-- Specify an alternative shape to use for given constraint terms (Gaussian is used if this is not specified) -->
<!-- Type: can be Gamma or Uniform -->
<!-- RelativeUncertainty: relative uncertainty on the shape -->
<!ELEMENT ConstraintTerm (#PCDATA)>
<!ATTLIST ConstraintTerm
        Type                  CDATA       #REQUIRED
        RelativeUncertainty   CDATA       #IMPLIED
>

<!-- Top element for channels. InputFile, HistoName and HistoPath
can be set at this level in which case they will become default to
all subsequent elements. Otherwise they can be set in individual
subelements -->
<!ELEMENT Channel (Data*,StatErrorConfig*,Sample+)>
<!-- InputFile: input file where the input histogram can be found (use abs path) -->
<!-- HistoPath: the path (within the root file) where the histogram can be found -->
<!-- HistoName: the name of the histogram to be used for this (and following in not overridden) item -->
<!ATTLIST Channel
        Name              CDATA            #REQUIRED
        InputFile         CDATA            #IMPLIED
        HistoPath         CDATA            #IMPLIED
        HistoName         CDATA            #IMPLIED
>

<!-- Data to be fit. If you don't provide it, Asimov data will be created -->
<!-- InputFile: any item set here will override the configuration for the subelements.
For this element there is no sublemenents so the setting will only have local effects -->
<!ELEMENT Data EMPTY>
<!ATTLIST Data
        InputFile         CDATA            #IMPLIED
        HistoPath         CDATA            #IMPLIED
        HistoName         CDATA            #IMPLIED
>

<!ELEMENT StatErrorConfig EMPTY>
<!ATTLIST StatErrorConfig
        RelErrorThreshold      CDATA            #IMPLIED
        ConstraintType         CDATA            #IMPLIED
>


<!-- Sample elements are made up of systematic variations -->
<!ELEMENT Sample (StatError | HistoSys | OverallSys | ShapeSys | NormFactor | ShapeFactor)*>
<!ATTLIST Sample
        Name              CDATA            #REQUIRED
        InputFile         CDATA            #IMPLIED
        HistoName         CDATA            #IMPLIED
        HistoPath         CDATA            #IMPLIED
        NormalizeByTheory      CDATA       #IMPLIED
>

<!-- Systematics for which the variation is provided by histograms -->
<!ELEMENT StatError EMPTY>
<!ATTLIST StatError
     Activate          CDATA            #REQUIRED
          HistoName         CDATA            #IMPLIED
          InputFile         CDATA            #IMPLIED
          HistoPath         CDATA            #IMPLIED
>

<!ELEMENT HistoSys EMPTY>
<!ATTLIST HistoSys
        Name              CDATA            #REQUIRED
        InputFile         CDATA            #IMPLIED
        HistoFileHigh     CDATA            #IMPLIED
        HistoPathHigh     CDATA            #IMPLIED
        HistoNameHigh     CDATA            #IMPLIED
        HistoFileLow      CDATA            #IMPLIED
        HistoPathLow      CDATA            #IMPLIED
        HistoNameLow      CDATA            #IMPLIED
>

<!-- Systematics for which the variation is provided by simple overall scaling -->
<!ELEMENT OverallSys EMPTY>
<!ATTLIST OverallSys
        Name              CDATA            #REQUIRED
        High              CDATA            #REQUIRED
        Low               CDATA            #REQUIRED
>

<!-- Systematics for which the variation is provided by simple overall scaling -->
<!ELEMENT ShapeSys EMPTY>
<!ATTLIST ShapeSys
          Name              CDATA            #REQUIRED
          HistoName         CDATA            #REQUIRED
          HistoPath         CDATA            #IMPLIED
          InputFile         CDATA            #IMPLIED
          ConstraintType    CDATA            #IMPLIED
>

<!-- Scaling factor, which may be the parameter of interest for cross section measurements-->
<!ELEMENT NormFactor EMPTY>
<!ATTLIST NormFactor
        Name              CDATA            #REQUIRED
        Val               CDATA            #REQUIRED
        High              CDATA            #REQUIRED
        Low               CDATA            #REQUIRED
        Const             CDATA            #IMPLIED
>


<!-- Systematics for which the variation is provided by simple overall scaling -->
<!ELEMENT ShapeFactor EMPTY>
<!ATTLIST ShapeFactor
          Name              CDATA            #REQUIRED
          Val               CDATA            #IMPLIED
          Low               CDATA            #IMPLIED
          High              CDATA            #IMPLIED
          Const             CDATA            #IMPLIED
          InputFile         CDATA            #IMPLIED
          HistoName         CDATA            #IMPLIED
          HistoPath         CDATA            #IMPLIED
>

=== root-project/root/tutorials/roostats/config/example_channel.xml
<!--
    Single channel configuration exampple.  
    The top level configuration XML is example.xml

    NormalizedByTheory should be "True" (not "TRUE" or "true") for all non-data-driven backgrounds.

    If you comment or remove the <Data> tag then it will use the expected data.

    Histogram inputs should be in pb and in top-level xml the lumi should be in 1/pb
    (The important thing is that they match... fb and 1/fb is also ok)

    Note: Config.dtd needs to be accessible.  It can be found in ROOT release area.  
    The file system path is relative to location of this XML file, not the executable.
-->

<!DOCTYPE Channel  SYSTEM 'HistFactorySchema.dtd'>

  <Channel Name="channel1" InputFile="./data/example.root" >
    <Data HistoName="data" HistoPath="" />

    <!-- Set the StatError type to Poisson.  Can also be Gaussian -->
    <StatErrorConfig RelErrorThreshold="0.05" ConstraintType="Poisson" />

    <Sample Name="signal" HistoPath="" HistoName="signal">
      <OverallSys Name="syst1" High="1.05" Low="0.95"/>
      <NormFactor Name="SigXsecOverSM" Val="1" Low="0." High="3."  />
    </Sample>
    <Sample Name="background1" HistoPath="" NormalizeByTheory="True" HistoName="background1">
      <StatError Activate="True" HistoName="background1_statUncert"  />
      <OverallSys Name="syst2" Low="0.95" High="1.05"/>
    </Sample>
    <Sample Name="background2" HistoPath="" NormalizeByTheory="True" HistoName="background2">
      <StatError Activate="True" /> <!-- Use Default Histogram Errors as input to StatError -->
      <OverallSys Name="syst3" Low="0.95" High="1.05"/>
      <!-- <HistoSys Name="syst4" HistoNameHigh="HighHistForSyst4" HistoNameLow="LowHistForSyst4"/>-->
    </Sample>
  </Channel>

=== root-project/root/tutorials/histfactory/example_DataDriven_controlRegion.xml
<!--
    Single channel configuration exampple.
    The top level configuration XML is example.xml

    NormalizedByTheory should be "True" (not "TRUE" or "true") for all non-data-driven backgrounds.

    If you comment or remove the <Data> tag then it will use the expected data.

    Histogram inputs should be in pb and in top-level xml the lumi should be in 1/pb
    (The important thing is that they match... fb and 1/fb is also ok)

    Note: Config.dtd needs to be accessible.  It can be found in ROOT release area.
    The file system path is relative to location of this XML file, not the executable.
-->

<!DOCTYPE Channel  SYSTEM 'HistFactorySchema.dtd'>

<!-- Notice that there is no signal in the control region -->

  <Channel Name="controlRegion" InputFile="./data/dataDriven.root"  >
    <Data HistoName="ControlRegion" HistoPath="" />

    <!-- Configure Stat Errors -->
    <StatErrorConfig RelErrorThreshold="0.05" ConstraintType="Gaussian" />

    <!-- MC Background in control region -->
    <!-- With StatError on MC Shape -->
    <Sample Name="background1" HistoPath="" NormalizeByTheory="True" HistoName="Background1" >
      <StatError Activate="True" />
      <OverallSys Name="bkg1CrossSection" Low="0.95" High="1.05"/>
    </Sample>

    <!-- Background 2 is completely DataDriven -->
    <!-- We fit its shape in this channel -->
    <!-- (As well as simultaneously in the signal region) -->
    <Sample Name="background2" HistoPath="" NormalizeByTheory="False" HistoName="FlatHist"  >
      <ShapeFactor Name="Bkg2Shape"/>
    </Sample>

  </Channel>

=== root-project/root/tutorials/histfactory/example_DataDriven_signalRegion.xml
<!--
    Single channel configuration exampple.
    The top level configuration XML is example.xml

    NormalizedByTheory should be "True" (not "TRUE" or "true") for all non-data-driven backgrounds.

    If you comment or remove the <Data> tag then it will use the expected data.

    Histogram inputs should be in pb and in top-level xml the lumi should be in 1/pb
    (The important thing is that they match... fb and 1/fb is also ok)

    Note: Config.dtd needs to be accessible.  It can be found in ROOT release area.
    The file system path is relative to location of this XML file, not the executable.
-->

<!DOCTYPE Channel  SYSTEM 'HistFactorySchema.dtd'>

  <Channel Name="signalRegion" InputFile="./data/dataDriven.root"  >
    <Data HistoName="data" HistoPath="" />

    <!-- Configure Stat Errors -->
    <StatErrorConfig RelErrorThreshold="0.05" ConstraintType="Gaussian" />

    <Sample Name="signal" HistoPath="" HistoName="Signal">
      <OverallSys Name="syst_signal" High="1.05" Low="0.95"/>
      <NormFactor Name="SigXsecOverSM" Val="1" Low=".2" High="1.5" />
    </Sample>

    <!-- This is MC Driven -->
    <Sample Name="background1" HistoPath="" NormalizeByTheory="True" HistoName="Background1"  >
      <StatError Activate="True" />
      <OverallSys Name="bkg1CrossSection" Low="0.95" High="1.05"/>
    </Sample>

    <!-- Background 2 is completely DataDriven -->
    <Sample Name="background2" HistoPath="" NormalizeByTheory="False" HistoName="FlatHist" >
      <OverallSys Name="syst_bkg2Extrapolation" Low="0.95" High="1.05"/>
      <ShapeFactor Name="Bkg2Shape" />
    </Sample>

  </Channel>
